name: Documentation

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout github repo
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: "3.11"
    - name: Lint
      uses: psf/black@stable
      with:
          version: "23.7.0"
    - name: Build docs
      run: |
        pip install --upgrade pip
        pip install -r ./docs/requirements.txt
        pip install sphinx
        sphinx-build docs ./docs/_build/html/
    - name: Checkout pages branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages
    - name: Commit documentation changes
      run: |
        cp -r docs/_build/html/* gh-pages/
        cp -r docs/*.pdf gh-pages/.
        cd gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        git push
